---
- name: create service dir
  file:
    path: "/etc/systemd/system/php{{ phpfpm_version_number }}-fpm.service.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: place override.conf
  template:
    src: systemd-override.j2
    dest: "/etc/systemd/system/php{{ phpfpm_version_number }}-fpm.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload php-fpm unit

- name: create directory {{ phpfpm_templates_dir }}/php-fpm
  file:
    path: "{{ phpfpm_templates_dir }}/php-fpm"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: place inital-setup script
  template:
    src: initial-setup.j2
    dest: "{{ phpfpm_templates_dir }}/php-fpm/initial-setup"
    owner: "root"
    group: "root"
    mode: 0750
